#' Estimate Relational Event Models (REMs)
#'
#' This function estimates Relational Event Models (REMs) using Maximum Likelihood Estimation (MLE) and Approximate Bayesian Regularization (ABR) with various priors. It processes a relational event history (REH) generated by `generate_reh()` and computes tie-oriented statistics to fit the specified model.
#'
#' @param edgelist A list output from `generate_reh()`, containing:
#'   - `edgelist`: A data frame of simulated events with columns `time`, `actor1`, and `actor2`.
#'   - `parameters`: A named list of model parameters.
#'   - `covar`: A data frame of actor covariates.
#'   - `directed`: Logical indicating whether the network is directed.
#' @param methods A character vector specifying the estimation methods. Options include:
#'   - `"mle"`: Maximum Likelihood Estimation.
#'   - `"abr_horseshoe"`: ABR with Horseshoe prior.
#'   - `"abr_ridge"`: ABR with Ridge prior.
#'   - `"abr_lasso"`: ABR with Lasso prior.
#'   Defaults to all methods.
#' @param seed An integer for reproducibility of random processes. Defaults to 123.
#'
#' @return A list with the following elements:
#'   - `coefs_mle`: Coefficients from the MLE model (if computed).
#'   - `coefs_abr_horseshoe`: ABR summary with Horseshoe prior (if computed).
#'   - `coefs_abr_ridge`: ABR summary with Ridge prior (if computed).
#'   - `coefs_abr_lasso`: ABR summary with Lasso prior (if computed).
#'   - `abr`: Raw ABR results for each prior type used.
#'   - `parameters`: Model parameters used for estimation.
#'   - `covar`: Actor covariates from the input REH.
#'   - `methods`: Methods used for estimation.
#'   - `directed`: Indicates whether the network is directed.
#'   - `seed`: Random seed used during the process.
#'
#' @details
#' The `estimate_rems()` function performs the following steps:
#'
#' 1. **Formula Generation**: It generates a formula for tie effects using `generate_formula()` based on the input parameters.
#' 2. **Statistics Computation**: Computes tie-oriented statistics using `remstats::remstats()` on the input REH.
#' 3. **MLE Estimation**: If `"mle"` is included in `methods`, the function estimates the model using `remstimate::remstimate()` and extracts the coefficients and covariance matrix for further processing.
#' 4. **ABR Estimation**: If `"abr_horseshoe"`, `"abr_ridge"`, or `"abr_lasso"` are included in `methods`, the function performs Approximate Bayesian Regularization using `shrinkem::shrinkem()` with the specified priors.
#'
#' **MLE Method**:
#' Estimates model parameters using maximum likelihood and calculates their covariance matrix. These estimates serve as priors for ABR methods.
#'
#' **ABR Method**:
#' Incorporates prior distributions to shrink model parameters. Three priors are supported:
#' - **Horseshoe**: Enforces sparsity in model coefficients.
#' - **Ridge**: Applies global shrinkage to all coefficients.
#' - **Lasso**: Promotes sparsity for interpretable results.
#'
#' Methods not included in `methods` are skipped.
#'
#' @note
#' This function assumes that the input REH is correctly formatted and generated by `generate_reh()`. Providing invalid inputs may result in errors.
#'
#' @examples
#' # Simulate a REH using generate_reh
#' parameters <- list(
#'   baseline = -5,
#'   send_z1 = 0.5,
#'   difference_z2 = 0.2,
#'   inertia = 0.3
#' )
#' covar <- data.frame(
#'   name = 1:10, time = 0,
#'   z1 = rnorm(10),
#'   z2 = rnorm(10)
#' )
#' reh <- generate_reh(parameters, covar, M = 20, directed = TRUE)
#'
#' # Estimate REMs
#' results <- estimate_rems(reh, methods = c("mle", "abr_horseshoe"))
#'
#' # View results
#' print(results$coefs_mle)                # MLE coefficients
#' print(results$coefs_abr_horseshoe)      # ABR Horseshoe summary
#'
#' @seealso
#' [generate_reh()] for generating relational event histories.
#' [remstats::remstats()] for computing tie-oriented statistics.
#' [remstimate::remstimate()] for estimating REMs using MLE.
#' [shrinkem::shrinkem()] for Approximate Bayesian Regularization.
#'
#' @export
estimate_rems <- function(edgelist,
                          methods = c("mle", "abr_horseshoe", "abr_ridge", "abr_lasso"),
                          seed = 123) {
  set.seed(seed)

  # Compute statistics
  effects <- generate_formula(edgelist$parameters)
  reh <- remify::remify(edgelist$edgelist,
                        directed = edgelist$directed,
                        model = "tie")
  statistics <- remstats::remstats(reh = reh,
                                   tie_effects = effects,
                                   attr_actors = edgelist$covar)

  result <- list()

  if ("mle" %in% methods) {
    # Estimate the MLE model
    mle <- remstimate::remstimate(
      reh = reh,
      stats = statistics,
      method = "MLE",
      timing = "interval"
    )
    result$coefs_mle <- summary(mle)$coefsTab
  }

  if (any(c("abr_horseshoe", "abr_ridge", "abr_lasso") %in% methods)) {
    # Estimate REMs with Approximate Bayesian Regularization
    estimates <- stats::coef(mle) # retrieve MLE estimates to provide to shrinkem
    cov <- mle$vcov # retrieve MLE covariance matrix to provide to shrinkem
    cov[upper.tri(cov)] <- t(cov)[upper.tri(cov)] # make sure the covariance matrix is symmetric

    if ("abr_horseshoe" %in% methods) {
      # Horseshoe Prior
      result$abr$abr_horseshoe <- shrinkem::shrinkem(estimates, cov, type = "horseshoe")
      result$coefs_abr_horseshoe <- summary(result$abr$abr_horseshoe)
    }

    if ("abr_ridge" %in% methods) {
      # Ridge Prior
      result$abr$abr_ridge <- shrinkem::shrinkem(estimates, cov, type = "ridge")
      result$coefs_abr_ridge <- summary(result$abr$abr_ridge)
    }

    if ("abr_lasso" %in% methods) {
      # Lasso Prior
      result$abr$abr_lasso <- shrinkem::shrinkem(estimates, cov, type = "lasso")
      result$coefs_abr_lasso <- summary(result$abr$abr_lasso)
    }
  }

  result$parameters <- edgelist$parameters
  result$covar <- edgelist$covar
  result$methods <- methods
  result$directed <- edgelist$directed
  result$seed <- seed

  return(result)

}
